[package]
name = "wasi3app"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
tokio = { version = "1.48.0", features = ["sync"] }
wasip3 = "0.2.0"
wit-bindgen = "0.46.0"
wit-bindgen-core = "0.46.0"

[lib]
crate-type = ["cdylib"]
