//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::auth_tokens::Entity as AuthTokens;
pub use super::device_tokens::Entity as DeviceTokens;
pub use super::dns_records::Entity as DnsRecords;
pub use super::sessions::Entity as Sessions;
pub use super::user_domains::Entity as UserDomains;
pub use super::users::Entity as Users;
