[package]
name = "selfupdater"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bollard = "0.19.2"
itertools = "0.14.0"
rustix = { version = "1.1.2", features = ["system"] }
tokio = { version = "1.47.1", features = ["full"] }
